CREATE TABLE `employees` (
  `id_employee` int(11) NOT NULL AUTO_INCREMENT,
  `employee_first_name` varchar(45) NOT NULL,
  `employee_last_name` varchar(45) NOT NULL,
  `employee_email` varchar(45) NOT NULL,
  `employee_phone_number` varchar(45) NOT NULL,
  `id_job` int(11) NOT NULL,
  `id_location` int(11) NOT NULL,
  `id_contract_active` int(11) DEFAULT NULL,
  `id_manager` int(11) DEFAULT NULL,
  `id_department` int(11) NOT NULL,
  `id_grade` int(11) NOT NULL,
  `is_manager` tinyint(4) NOT NULL,
  `is_officer` tinyint(4) NOT NULL,
  `is_active` tinyint(4) NOT NULL,
  `id_project_1` int(11) DEFAULT NULL,
  `id_project_2` int(11) DEFAULT NULL,
  `id_project_3` int(11) DEFAULT NULL,
  `id_project_4` int(11) DEFAULT NULL,
  `id_project_5` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_employee`),
  KEY `id_job_e_idx` (`id_job`),
  KEY `id_location_e_idx` (`id_location`),
  KEY `id_contract_idx` (`id_contract_active`),
  KEY `id_project_e_1_idx` (`id_project_1`),
  KEY `id_project_e_2_idx` (`id_project_2`),
  KEY `id_project_e_3_idx` (`id_project_3`),
  KEY `id_project_e_4_idx` (`id_project_4`),
  KEY `id_project_e_5_idx` (`id_project_5`),
  KEY `id_manager_e_idx` (`id_manager`),
  KEY `id_department_e_idx` (`id_department`),
  KEY `id_grade_e_idx` (`id_grade`),
  CONSTRAINT `id_contract_e` FOREIGN KEY (`id_contract_active`) REFERENCES `contracts` (`id_contract`),
  CONSTRAINT `id_department_e` FOREIGN KEY (`id_department`) REFERENCES `departments` (`id_department`),
  CONSTRAINT `id_grade_e` FOREIGN KEY (`id_grade`) REFERENCES `grades` (`id_grade`),
  CONSTRAINT `id_job_e` FOREIGN KEY (`id_job`) REFERENCES `jobs` (`id_job`),
  CONSTRAINT `id_location_e` FOREIGN KEY (`id_location`) REFERENCES `locations` (`id_location`),
  CONSTRAINT `id_manager_e` FOREIGN KEY (`id_manager`) REFERENCES `managers` (`id_manager`),
  CONSTRAINT `id_project_e_1` FOREIGN KEY (`id_project_1`) REFERENCES `projects` (`id_project`),
  CONSTRAINT `id_project_e_2` FOREIGN KEY (`id_project_2`) REFERENCES `projects` (`id_project`),
  CONSTRAINT `id_project_e_3` FOREIGN KEY (`id_project_3`) REFERENCES `projects` (`id_project`),
  CONSTRAINT `id_project_e_4` FOREIGN KEY (`id_project_4`) REFERENCES `projects` (`id_project`),
  CONSTRAINT `id_project_e_5` FOREIGN KEY (`id_project_5`) REFERENCES `projects` (`id_project`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci